- seid: 0
  pdrs:
  - pdrID: 0
    precedence: 0
    pdi:
      sourceInterface: Access
      networkInstance: access
      localFTEID:
        teid: 1234
        ip4: 172.20.16.2
      ueIPAddress:
        isDestination: false
        ip4: 10.10.10.10
    outerHeaderRemoval: OUTER_HEADER_GTPU_UDP_IPV4
    farID: 12
  fars:
  - farID: 12
    applyAction: Forward
    forwardingParameters:
      destinationInterface: SGiLAN
      networkInstance: sgi1
- seid: 1
  pdrs:
  - pdrID: 1
    precedence: 0
    pdi:
      sourceInterface: SGiLAN
      networkInstance: sgi1
      ueIPAddress:
        isDestination: true
        ip4: 10.10.10.10
      sdfFilter:
        flowDescription: 'permit in ip from 0.0.0.0/0  to 0.0.0.0/0'
    farID: 13
  fars:
  - farID: 13
    applyAction: Forward
    forwardingParameters:
      destinationInterface: Access
      networkInstance: access
      outerHeaderCreation:
        desc: OUTER_HEADER_CREATION_GTPU_UDP_IPV4
        teid: 4321
        ip: 172.20.16.3

- seid: 2
  pdrs:
  - pdrID: 2
    precedence: 0
    pdi:
      sourceInterface: Access
      networkInstance: access
      localFTEID:
        teid: 5678
        ip4: 172.20.16.2
      ueIPAddress:
        isDestination: false
        ip4: 20.20.20.20
    outerHeaderRemoval: OUTER_HEADER_GTPU_UDP_IPV4
    farID: 14
  fars:
  - farID: 14
    applyAction: Forward
    forwardingParameters:
      destinationInterface: SGiLAN
      networkInstance: sgi2
- seid: 3
  pdrs:
  - pdrID: 3
    precedence: 0
    pdi:
      sourceInterface: SGiLAN
      networkInstance: sgi2
      ueIPAddress:
        isDestination: true
        ip4: 20.20.20.20
      sdfFilter:
        flowDescription: 'permit in ip from 0.0.0.0/0  to 0.0.0.0/0'
    farID: 15
  fars:
  - farID: 15
    applyAction: Forward
    forwardingParameters:
      destinationInterface: Access
      networkInstance: access
      outerHeaderCreation:
        desc: OUTER_HEADER_CREATION_GTPU_UDP_IPV4
        teid: 8765
        ip: 172.20.16.3
